version: '3'
services:
  pdb:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    network_mode: "host"

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/var/lib/redis/data'
    network_mode: "host"

  api:
    build:
      context: app
      dockerfile: Dockerfile-api
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - pdb
    network_mode: "host"

  worker:
    build:
      context: app
      dockerfile: Dockerfile-worker
    depends_on:
      - redis
      - pdb
    network_mode: "host"

volumes:
  db:
    driver: local
  redis_data:
