version: '3'
services:
  pdb:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/var/lib/redis/data'
volumes:
  db:
    driver: local
  redis_data:
