FROM python:3.8

RUN apt-get update && apt-get -y install libpq-dev gcc && pip install psycopg2

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["rq", "worker", "--url", "redis://redis:6379"]
