# Use a Python base image
FROM python:3.8

# Set the working directory within the container
WORKDIR /app

# Copy the Python dependencies
COPY requirements.txt .

# Install the required Python packages
RUN pip install --no-cache-dir -r requirements.txt

# Install gunicorn
RUN pip install gunicorn

# Copy the worker code and database_file.py
COPY worker.py .
COPY database_file.py .

# Run the background worker using gunicorn
CMD ["python", "-u","worker.py"]
